baseURL = "https://alex.bouma.dev/"
languageCode = "en-us"
title = "Alex Bouma"
theme = "terminal"
author = "Alex Bouma"
paginate = 10
disqusShortname = "alexbouma"
enableRobotsTXT = true

[params]
  author = "Alex Bouma"
  tagline = "PHP artisan, full stack developer and server lover | Founder @simulise | Building https://chief.app"
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 6
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Alex Bouma"
    subtitle = "Entrepreneur, developer and artisan"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Alex Bouma"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "public-key"
        name = "Public key"
        url = "/public-key"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "chief"
        name = "Chief Tools"
        url = "https://chief.app/"
        weight = 100
      [[languages.en.menu.main]]
        identifier = "social-github"
        name = "GitHub"
        url = "https://github.com/stayallive"
        weight = 200
      [[languages.en.menu.main]]
        identifier = "social-twitter"
        name = "Twitter"
        url = "https://twitter.com/stayallive"
        weight = 200
